# Github workflow to test forty_seven

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    uses: nivlekp/pang/.github/workflow-templates/composition-ci.yml
